worker_processes auto;
events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;

  resolver 127.0.0.11 valid=5s ipv6=off;

  log_format main '$remote_addr "$request" $status upstream=$upstream_addr rt=$request_time';
  access_log /var/log/nginx/access.log main;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /        { try_files /index.html =404; }
    location = /style.css { try_files /style.css =404; }
    location = /app.js  { try_files /app.js =404; }

   location /auth/ {
      set $upstream_auth http://auth-service:8000;
      proxy_pass $upstream_auth;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /products {
      set $upstream_products http://product-service:8000;
      proxy_pass $upstream_products;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /products/ {
      set $upstream_products http://product-service:8000;
      proxy_pass $upstream_products;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /users {
      set $upstream_users http://user-service:8000;
      proxy_pass $upstream_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /users/ {
      set $upstream_users http://user-service:8000;
      proxy_pass $upstream_users;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /chat/ {
      set $upstream_chat http://chat-service:8000;
      proxy_pass $upstream_chat;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /orders {
      set $upstream_orders http://order-service:8000;
      proxy_pass $upstream_orders;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }
    location /orders/ {
      set $upstream_orders http://order-service:8000;
      proxy_pass $upstream_orders;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
